spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/testdb
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  thymeleaf3.decoupled-logic: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      data-locations: classpath:data2.sql
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
